import { Contestant } from "./new";

export const cast: Contestant[] = [
  {
    Name: "Adam Riley",
    Age: 36,
    Gender: "Male",
    Hometown: "Fayetteville, Arkansas",
    Country: "United States",
    Status: "Competing",
    "Reason they tapped out": "",
    "Ref.": "[24]",
  },
  {
    Name: "Teimojin Tan",
    Age: 31,
    Gender: "Male",
    Hometown: "Montreal, Quebec",
    Country: "Canada",
    Status: "Competing",
    "Reason they tapped out": "",
    "Ref.": "",
  },
  {
    Name: "Jessie Krebs",
    Age: 49,
    Gender: "Female",
    Hometown: "Pagosa Springs, Colorado",
    Country: "United States",
    Status: "Competing",
    "Reason they tapped out": "",
    "Ref.": "",
  },
  {
    Name: "Juan Pablo Quiñonez",
    Age: 30,
    Gender: "Male",
    Hometown: "Pinawa, Manitoba",
    Country: "Canada",
    Status: "Competing",
    "Reason they tapped out": "",
    "Ref.": "",
  },
  {
    Name: "Karie Lee Knoke",
    Age: 57,
    Gender: "Female",
    Hometown: "Sandpoint, Idaho",
    Country: "United States",
    Status: "Competing",
    "Reason they tapped out": "",
    "Ref.": "",
  },
  {
    Name: "Terry Burns",
    Age: 30,
    Gender: "Male",
    Hometown: "Homer, Alaska",
    Country: "United States",
    Status: "Competing",
    "Reason they tapped out": "",
    "Ref.": "",
  },
  {
    Name: "Tom Garstang",
    Age: 35,
    Gender: "Male",
    Hometown: "Earlysville, Virginia",
    Country: "United States",
    Status: "Competing",
    "Reason they tapped out": "",
    "Ref.": "",
  },
  {
    Name: "Benji Hill",
    Age: 46,
    Gender: "Male",
    Hometown: "Bellevue, Idaho",
    Country: "United States",
    Status: "27 days (medically evacuated)",
    "Reason they tapped out": "Giardia infection",
    "Ref.": "",
  },
  {
    Name: "Igor Limansky",
    Age: 34,
    Gender: "Male",
    Hometown: "Salt Lake City, Utah",
    Country: "United States",
    Status: "20 days",
    "Reason they tapped out": "Heart palpitations, Exhaustion",
    "Ref.": "",
  },
  {
    Name: "Jacques Turcotte",
    Age: 23,
    Gender: "Male",
    Hometown: "Juneau, Alaska",
    Country: "United States",
    Status: "15 days",
    "Reason they tapped out": "Missed Family",
    "Ref.": "",
  },
].map((x) => {
  return {
    ...x,
    image: `/images/alone-cast/Alone_Season_9_Cast_Bio_${
      x.Name.split(" ")[0]
    }.jpeg`,
  };
});
